name: Data Model Generator

on:
  workflow_dispatch:
  workflow_call:

jobs:
  vars:
    name: Set Variables
    outputs:
      user: ${{ steps.data.outputs.user }}
      pass: ${{ steps.data.outputs.pass }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Generate random username and password
        id: data
        run: |
          USERNAME="user$(shuf -i 1000-9999 -n 1)"
          PASSWORD=$(openssl rand -base64 12)

          echo "user=$USERNAME" >> $GITHUB_OUTPUT
          echo "pass=$PASSWORD" >> $GITHUB_OUTPUT

  schemaspy:
    name: Generate Documentation
    runs-on: ubuntu-22.04
    needs: [vars]
    services:
      postgres:
        image: postgis/postgis:17-master
        env:
          POSTGRES_DB: fp
          POSTGRES_USER: ${{ needs.vars.outputs.user }}
          POSTGRES_PASSWORD: ${{ needs.vars.outputs.pass }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Flyway
        uses: docker://flyway/flyway:11-alpine
        env:
          FLYWAY_URL: jdbc:postgresql://postgres:5432/fp
          FLYWAY_USER: ${{ needs.vars.outputs.user }}
          FLYWAY_PASSWORD: ${{ needs.vars.outputs.pass }}
          FLYWAY_LOCATIONS: filesystem:./database-migrations/sql
          FLYWAY_DEFAULT_SCHEMA: "app_fp"
          FLYWAY_BASELINE_ON_MIGRATE: true
          FLYWAY_PLACEHOLDERS_api_db_username: fp_api_dbuser
          FLYWAY_PLACEHOLDERS_api_db_password: test
        with:
          args: -X info migrate info

      - name: Create Output Folder
        run: |
          mkdir -p output
          chmod a+rwx -R output

      - name: Run Schemaspy
        run: docker run --network host -v "$PWD/output:/output" schemaspy/schemaspy:6.2.4 -t pgsql11 -db fp -host 127.0.0.1 -port 5432 -u ${{ needs.vars.outputs.user }} -p ${{ needs.vars.outputs.pass }} -schemas app_fp -X "create_date|update_date|create_user|update_user|revision_count"

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output